### ISSUE TITLE
"Add Field" text can't be translated

### ISSUE THREAD

**Issue by luixal** [ohmyform/ui#24]
Hi,

I've just sent a PR with some changes to spanish translation and noticed that the text _"Add Field"_ at [fields.tab.tsx#77](https://github.com/ohmyform/ui/blob/6c59b71f8640cc8a1f1a831eac7b31f7e61233a6/components/form/admin/fields.tab.tsx#L77) can't be translated as it's hardcoded:

```
<PlusOutlined /> Add Field
```

**Comment by wodka** [comment]
good point, added translation right now
